robot_base_frame: base_link

transform_tolerance: 5

footprint: [[0.6, -0.245], [0.6, 0.245], [0, 0.245], [0, -0.245]]
inflation_radius: 1.0
#robot_radius: 0.18
#inflater:
#  robot_radius: 0.18
#  inflation_radius: 0.24

obstacles:
  observation_sources: base_scan
  base_scan:
    sensor_frame: laser
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    inf_is_valid: true
    obstacle_range: 5
    raytrace_range: 10
    min_obstacle_height: -0.1
    max_obstacle_height: 1.0
