global_frame: map #odom -okay

rolling_window: true
publish_frequency: 10.0 #5.0 -okay

width: 5.0
height: 5.0
resolution: 0.025

plugins:
 - {name: obstacles, type: "costmap_2d::VoxelLayer"}
 - {name: inflater, type: "costmap_2d::InflationLayer"}
